include:
  - board: nice_nano_v2
    shield: sambobbarnes_left
    snippet: zmk-usb-logging # TODO: remove me
  - board: nice_nano_v2
    shield: sambobbarnes_right
  - board: nice_nano_v2
    shield: settings_reset
