# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_INVERT=n

# Battery
CONFIG_ZMK_BATTERY=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=30000
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_BATTERY_REPORTING=y

# Usb
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y

# Bluetooth
CONFIG_BT=Y
CONFIG_ZMK_BLE_PRIORITY=n
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Key debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=20
